
package com.matic.people;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T17:14:48.818+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class CXFWeb_CXFWebPort_Client {

    private static final QName SERVICE_NAME = new QName("http://web.matic.com/", "CXFWebService");

    private CXFWeb_CXFWebPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CXFWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CXFWebService ss = new CXFWebService(wsdlURL, SERVICE_NAME);
        CXFWeb port = ss.getCXFWebPort();  
        
        {
        System.out.println("Invoking addPeople...");
        com.matic.people.People _addPeople_arg0 = null;
        boolean _addPeople__return = port.addPeople(_addPeople_arg0);
        System.out.println("addPeople.result=" + _addPeople__return);


        }

        System.exit(0);
    }

}
