
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.matic.people;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T17:14:48.837+08:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CXFWebService",
                      portName = "CXFWebPort",
                      targetNamespace = "http://web.matic.com/",
                      wsdlLocation = "http://10.83.33.106:8080/WebService/service/addPeople?wsdl",
                      endpointInterface = "com.matic.people.CXFWeb")
                      
public class CXFWebImpl implements CXFWeb {

    private static final Logger LOG = Logger.getLogger(CXFWebImpl.class.getName());

    /* (non-Javadoc)
     * @see com.matic.people.CXFWeb#addPeople(com.matic.people.People  arg0 )*
     */
    public boolean addPeople(com.matic.people.People arg0) { 
        LOG.info("Executing operation addPeople");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
