package com.matic.people;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T17:14:48.860+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CXFWebService", 
                  wsdlLocation = "http://10.83.33.106:8080/WebService/service/addPeople?wsdl",
                  targetNamespace = "http://web.matic.com/") 
public class CXFWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.matic.com/", "CXFWebService");
    public final static QName CXFWebPort = new QName("http://web.matic.com/", "CXFWebPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.83.33.106:8080/WebService/service/addPeople?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CXFWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.83.33.106:8080/WebService/service/addPeople?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CXFWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CXFWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CXFWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CXFWeb
     */
    @WebEndpoint(name = "CXFWebPort")
    public CXFWeb getCXFWebPort() {
        return super.getPort(CXFWebPort, CXFWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXFWeb
     */
    @WebEndpoint(name = "CXFWebPort")
    public CXFWeb getCXFWebPort(WebServiceFeature... features) {
        return super.getPort(CXFWebPort, CXFWeb.class, features);
    }

}
