package com.matic.people;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T17:14:48.847+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://web.matic.com/", name = "CXFWeb")
@XmlSeeAlso({ObjectFactory.class})
public interface CXFWeb {

    @WebMethod
    @RequestWrapper(localName = "addPeople", targetNamespace = "http://web.matic.com/", className = "com.matic.people.AddPeople")
    @ResponseWrapper(localName = "addPeopleResponse", targetNamespace = "http://web.matic.com/", className = "com.matic.people.AddPeopleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addPeople(
        @WebParam(name = "arg0", targetNamespace = "")
        com.matic.people.People arg0
    );
}
