package com.matic.cxfhello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T15:08:23.561+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://web.matic.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://web.matic.com/", className = "com.matic.cxfhello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://web.matic.com/", className = "com.matic.cxfhello.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
