
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.matic.cxfhello;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T15:08:23.551+08:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloServiceService",
                      portName = "HelloServicePort",
                      targetNamespace = "http://web.matic.com/",
                      wsdlLocation = "http://10.83.33.106:8080/WebService/service/helloService?wsdl",
                      endpointInterface = "com.matic.cxfhello.HelloService")
                      
public class HelloServiceImpl implements HelloService {

    private static final Logger LOG = Logger.getLogger(HelloServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.matic.cxfhello.HelloService#sayHello(java.lang.String  arg0 )*
     */
    public java.lang.String sayHello(java.lang.String arg0) { 
        LOG.info("Executing operation sayHello");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
