
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.matic.cxfinterface;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:56:11.522+08:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CXFInterfaceService",
                      portName = "CXFInterfacePort",
                      targetNamespace = "http://service.matic.com/",
                      wsdlLocation = "http://10.83.33.106:8011/WebService/CXFInterfaceImpl?wsdl",
                      endpointInterface = "com.matic.cxfinterface.CXFInterface")
                      
public class CXFInterfaceImpl implements CXFInterface {

    private static final Logger LOG = Logger.getLogger(CXFInterfaceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.matic.cxfinterface.CXFInterface#test1(java.lang.String  arg0 )*
     */
    public java.lang.String test1(java.lang.String arg0) { 
        LOG.info("Executing operation test1");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
