package com.matic.cxfinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:56:11.543+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CXFInterfaceService", 
                  wsdlLocation = "http://10.83.33.106:8011/WebService/CXFInterfaceImpl?wsdl",
                  targetNamespace = "http://service.matic.com/") 
public class CXFInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.matic.com/", "CXFInterfaceService");
    public final static QName CXFInterfacePort = new QName("http://service.matic.com/", "CXFInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.83.33.106:8011/WebService/CXFInterfaceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CXFInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.83.33.106:8011/WebService/CXFInterfaceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CXFInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CXFInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CXFInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CXFInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CXFInterface
     */
    @WebEndpoint(name = "CXFInterfacePort")
    public CXFInterface getCXFInterfacePort() {
        return super.getPort(CXFInterfacePort, CXFInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXFInterface
     */
    @WebEndpoint(name = "CXFInterfacePort")
    public CXFInterface getCXFInterfacePort(WebServiceFeature... features) {
        return super.getPort(CXFInterfacePort, CXFInterface.class, features);
    }

}
