package com.matic.cxfinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:56:11.531+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.matic.com/", name = "CXFInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface CXFInterface {

    @WebMethod
    @RequestWrapper(localName = "test1", targetNamespace = "http://service.matic.com/", className = "com.matic.cxfinterface.Test1")
    @ResponseWrapper(localName = "test1Response", targetNamespace = "http://service.matic.com/", className = "com.matic.cxfinterface.Test1Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String test1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
