
package com.matic.cxfinterface;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:56:11.537+08:00
 * Generated source version: 2.4.2
 * 
 */
 
public class CXFInterface_CXFInterfacePort_Server{

    protected CXFInterface_CXFInterfacePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CXFInterfaceImpl();
        String address = "http://10.83.33.106:8011/WebService/CXFInterfaceImpl";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CXFInterface_CXFInterfacePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
