
package com.matic.cxfinterface;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:56:11.504+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class CXFInterface_CXFInterfacePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.matic.com/", "CXFInterfaceService");

    private CXFInterface_CXFInterfacePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CXFInterfaceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CXFInterfaceService ss = new CXFInterfaceService(wsdlURL, SERVICE_NAME);
        CXFInterface port = ss.getCXFInterfacePort();  
        
        {
        System.out.println("Invoking test1...");
        java.lang.String _test1_arg0 = "";
        java.lang.String _test1__return = port.test1(_test1_arg0);
        System.out.println("test1.result=" + _test1__return);


        }

        System.exit(0);
    }

}
