
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.matic.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:41:21.584+08:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CXFServiceService",
                      portName = "CXFServicePort",
                      targetNamespace = "http://service.matic.com/",
                      wsdlLocation = "http://10.83.33.106:8010/WebService/CXFService?wsdl",
                      endpointInterface = "com.matic.cxf.CXFService")
                      
public class CXFServiceImpl implements CXFService {

    private static final Logger LOG = Logger.getLogger(CXFServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.matic.cxf.CXFService#hello(java.lang.String  arg0 )*
     */
    public java.lang.String hello(java.lang.String arg0) { 
        LOG.info("Executing operation hello");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
