
package com.matic.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-29T13:41:21.601+08:00
 * Generated source version: 2.4.2
 * 
 */
 
public class CXFService_CXFServicePort_Server{

    protected CXFService_CXFServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CXFServiceImpl();
        String address = "http://10.83.33.106:8010/WebService/CXFService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CXFService_CXFServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
