
package com.matic.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://service.matic.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://service.matic.com/", className = "com.matic.client.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://service.matic.com/", className = "com.matic.client.HelloResponse")
    @Action(input = "http://service.matic.com/Service/HelloRequest", output = "http://service.matic.com/Service/HelloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
